const Data = [
  {
    title: "100 Days of Code: The Complete Python Pro Bootcamp",
    details:
      "Master Python by building 100 projects in 100 days. Learn data science, automation, build websites, games and apps!",
    instructor: "Dr. Angela Yu, Developer and Lead Instructor",
    rating: 4.7,
    students: 309586,
    price: "449",
    originalprice: "3,099",
    image: "https://img-c.udemycdn.com/course/240x135/2776760_f176_10.jpg",
    bestseller: true,
  },
  {
    title: "JavaScript Algorithms and Data Structures Masterclass",
    details: "The Missing Computer Science and Coding Interview Bootcamp",
    instructor: "Colt Steele",
    rating: 4.7,
    students: 28032,
    price: "599",
    originalprice: "4,099",
    image: "https://img-c.udemycdn.com/course/240x135/1406344_1d65_3.jpg",
    bestseller: false,
  },
  {
    title: "Competitive Programming Essentials, Master Algorithms",
    details:
      "Master competitive coding techniques - maths, number theory, dynamic programming, advanced data structures &amp; algorithms",
    rating: 4.4,
    instructor: "Prateek Narang, Apaar Kamal, Coding Minutes",
    students: 2194,
    price: "449",
    originalprice: "3,099",
    image: "https://img-c.udemycdn.com/course/240x135/4087810_2aaf.jpg",
    bestseller: false,
  },
  {
    title: "JavaScript - The Complete Guide 2024 (Beginner + Advanced)",
    details:
      "Modern JavaScript from the beginning - all the way up to JS expert level! THE must-have JavaScript resource in 2024.",
    instructor: "Academind by Maximilian Schwarzmüller",
    rating: 4.6,
    students: 29933,
    price: "699",
    originalprice: "4,999",
    image: "https://img-c.udemycdn.com/course/240x135/2508942_11d3_3.jpg",
    bestseller: false,
  },
  {
    title: "Node.js, Express, MongoDB & More: The Complete Bootcamp",
    details:
      "Master Node by building a real-world RESTful API and web app (with authentication, Node.js security, payments & more)",
    instructor: "Jonas Schmedtmann",
    rating: 4.6,
    students: 24491,
    price: "499",
    originalprice: "3499",
    image: "https://img-c.udemycdn.com/course/240x135/1672410_9ff1_5.jpg",
    bestseller: true,
  },
  {
    title: "The Ultimate React Course 2024: React, Next.js, Redux & More",
    details:
      "Master modern React from beginner to advanced! Next.js, Context API, React Query, Redux, Tailwind, advanced patterns",
    rating: 4.7,
    students: 13320,
    price: "499",
    originalprice: "799",
    image: "https://img-c.udemycdn.com/course/240x135/4471614_361e_8.jpg",
    bestseller: true,
  },
  {
    title: "Complete Mathematics Masterclass: College & University Level",
    details:
      "All the Applied Mathematics Needed in Science, Programming, Engineering, IT & Business - Theory, Examples & Exercises",
    rating: 4.5,
    students: 511,
    price: "449",
    originalprice: "3,099",
    instructor: "Dr. Börge Göbel",
    image: "https://img-c.udemycdn.com/course/240x135/3953742_c816_3.jpg",
  },
  {
    title: "Java Spring Framework 6 with Spring Boot 3",
    details:
      "Master Java, Spring 6 and Spring Boot 3 with JDBC, JPA, Security, Docker and Microservices with Telusko",
    rating: 4.6,
    students: 18892,
    price: "499",
    originalprice: "3,499",
    instructor: "Navin Reddy",
    image: "https://img-c.udemycdn.com/course/240x135/2167814_a0e6_5.jpg",
  },
  {
    title: "Master statistics & machine learning: intuition, math, code",
    details:
      "A rigorous and engaging deep-dive into statistics and machine-learning, with hands-on applications in Python and MATLAB.",
    instructor: "Mike X Cohen",
    rating: 4.8,
    students: 2389,
    price: "499",
    originalprice: "3,499",
    image: "https://img-c.udemycdn.com/course/240x135/3160664_ef7f_3.jpg",
  },
];
export default Data;
